name: Update my Readme.md

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'
  push:
    branches:
      - 'main'


jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Gekitsuu Git Repo
        uses: actions/checkout@v3
      
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Setup Python Poetry
        uses: Gr1N/setup-poetry@v8
      
      - name: Install Project dependencies
        run: poetry install
      
      - name: Build README.md file
        run: poetry run -- python ./make_readme.py

      - id: commit_files
        name: Commit files  
        run:
          git config --local user.name "Adam Glenn"
          git config --local user.email "gekitsuu@gmail.com"
          if ! git diff --exit-code; then
              git add README.md
              git commit -am "GH Action Files added $(date)"
              git push -f origin main
          fi
      